# These are supported funding model platforms

#github: [xinlake]
custom: ["https://www.paypal.com/paypalme/xinlake", "https://xinlake.dev/assets/images/donate/alipay.jpg", "https://xinlake.dev/assets/images/donate/weixin.png"]
